package transporthib;
// Generated 31-ene-2017 17:48:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private String postalcode;
     private String name;
     private Set packages = new HashSet(0);

    public City() {
    }

	
    public City(String postalcode, String name) {
        this.postalcode = postalcode;
        this.name = name;
    }
    public City(String postalcode, String name, Set packages) {
       this.postalcode = postalcode;
       this.name = name;
       this.packages = packages;
    }
   
    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPackages() {
        return this.packages;
    }
    
    public void setPackages(Set packages) {
        this.packages = packages;
    }




}


