package transporthib;
// Generated 31-ene-2017 17:48:25 by Hibernate Tools 4.3.1



/**
 * Package generated by hbm2java
 */
public class Package  implements java.io.Serializable {


     private Integer idpackage;
     private City city;
     private Truckdriver truckdriver;
     private String customer;

    public Package() {
    }

    public Package(City city, Truckdriver truckdriver, String customer) {
       this.city = city;
       this.truckdriver = truckdriver;
       this.customer = customer;
    }
   
    public Integer getIdpackage() {
        return this.idpackage;
    }
    
    public void setIdpackage(Integer idpackage) {
        this.idpackage = idpackage;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Truckdriver getTruckdriver() {
        return this.truckdriver;
    }
    
    public void setTruckdriver(Truckdriver truckdriver) {
        this.truckdriver = truckdriver;
    }
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    @Override
    public String toString() {
        return "Package{" + "idpackage=" + idpackage + ", city=" + city.getPostalcode() + ", truckdriver=" + truckdriver.getDni() + ", customer=" + customer + '}';
    }




}


