package transporthib;
// Generated 31-ene-2017 17:48:25 by Hibernate Tools 4.3.1



/**
 * Truck generated by hbm2java
 */
public class Truck  implements java.io.Serializable {


     private String idtruck;
     private Truckdriver truckdriver;
     private String model;
     private int capacity;

    public Truck() {
    }

    public Truck(String idtruck, Truckdriver truckdriver, String model, int capacity) {
       this.idtruck = idtruck;
       this.truckdriver = truckdriver;
       this.model = model;
       this.capacity = capacity;
    }
   
    public String getIdtruck() {
        return this.idtruck;
    }
    
    public void setIdtruck(String idtruck) {
        this.idtruck = idtruck;
    }
    public Truckdriver getTruckdriver() {
        return this.truckdriver;
    }
    
    public void setTruckdriver(Truckdriver truckdriver) {
        this.truckdriver = truckdriver;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    @Override
    public String toString() {
        return "Truck{" + "idtruck=" + idtruck + ", model=" + model + ", capacity=" + capacity + '}';
    }




}


